# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# cyberdream theme for lazygit
gui:
    nerdFontsVersion: "3"

# to skip without creating a new repo
notARepository: 'skip'
