"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:color_yellow)\
$os\
$username\
[](fg:color_yellow bg:color_blue)\
$directory\
[](fg:color_blue bg:color_cyan)\
$git_branch\
$git_status\
[](fg:color_cyan bg:color_magenta)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$elixir\
[](fg:color_magenta bg:color_purple)\
$docker_context\
$conda\
[](fg:color_purple bg:color_bg3)\
$time\
[ ](fg:color_bg3)\
$line_break$character"""

palette = 'cyberdream'

[palettes.cyberdream]
color_fg0 = '#ffffff'
color_bg0 = '#16181a'
color_bg1 = '#1e2124'
color_bg3 = '#3c4048'
color_blue = '#5ea1ff'
color_cyan = '#5ef1ff'
color_green = '#5eff6c'
color_yellow = '#f1ff5e'
color_orange = '#ffbd5e'
color_red = '#ff6e5e'
color_pink = "#ff5ea0"
color_magenta = "#ff5ef1"
color_purple = '#bd5eff'

[os]
disabled = false
style = "bg:color_yellow fg:color_bg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_yellow fg:color_bg0"
style_root = "bg:color_yellow fg:color_bg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg0 bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_bg0 bg:color_cyan)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_bg0 bg:color_cyan)]($style)'

[nodejs]
symbol = ""
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[c]
symbol = " "
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[rust]
symbol = ""
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[golang]
symbol = ""
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[php]
symbol = ""
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[java]
symbol = " "
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[kotlin]
symbol = ""
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[haskell]
symbol = ""
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[python]
symbol = ""
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[elixir]
symbol = " "
style = "bg:color_magenta"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_magenta)]($style)'

[docker_context]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $context) ](fg:color_bg0 bg:color_purple)]($style)'

[conda]
style = "bg:color_purple"
format = '[[ $symbol( $environment) ](fg:color_bg0 bg:color_purple)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg3"
format = '[[   $time ](fg:color_fg0 bg:color_bg3)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[custom.toolbox]
description = "The activated toolbox container"
command = "echo $(. /var/run/.containerenv; echo ${name} ${DISTTAG%container})"
when = """ [[ -f /run/.containerenv && -f /run/.toolboxenv ]] """
style = "bg:color_purple2 fg:color_fg0"
format = "[  $output ]($style)"
disabled = false
